include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = fanqiehehePrefs

fanqiehehePrefs_FILES = FQHRootListController.m
fanqiehehePrefs_FRAMEWORKS = UIKit Foundation
fanqiehehePrefs_PRIVATE_FRAMEWORKS = Preferences
fanqiehehePrefs_INSTALL_PATH = /Library/PreferenceBundles

include $(THEOS_MAKE_PATH)/bundle.mk
